version: '3.1'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: movies
    volumes:
      ./init.sql:/docker-entrypoint-initdb.d/init.sql